In [7]:
import numpy as np
import pandas as pd

import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

from sklearn import svm

In [2]:
data = pd.read_csv('/content/heart_dataset.csv')
data.head(10)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   
5  90.0        1                        47         0                 40   
6  75.0        1                       246         0                 15   
7  60.0        1                       315         1                 60   
8  65.0        0                       157         0                 65   
9  80.0        1                       123         0                 35   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   
5                    1  204000.00               2.1           132    1   
6                    0  127000.00               1.2           137    1   
7                    0  454000.00               1.1           131    1   
8                    0  263358.03               1.5           138    0   
9                    1  388000.00               9.4           133    1   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1  
5        1     8            1  
6        0    10            1  
7        1    10            1  
8        0    10            1  
9        1    10            1

In [3]:
data.describe()

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  \
count         299.00000    299.000000  299.000000  299.00000  299.000000   
mean            1.39388    136.625418    0.648829    0.32107  130.260870   
std             1.03451      4.412477    0.478136    0.46767   77.614208   
min             0.50000    113.000000    0.000000    0.00000    4.000000   
25%             0.90000    134.000000    0.000000    0.00000   73.000000   
50%             1.10000    137.000000    1.000000    0.00000  115.000000   
75%             1.40000    140.000000    1.000000    1.00000  203.000000   
max             9.40000    148.000000    1.000000    1.00000  285.000000   

       DEATH_EVENT  
count    299.00000  
mean       0.32107  
std        0.46767  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        1.00000  
max        1.00000

In [8]:
inp_data = data.drop(data[["DEATH_EVENT"]], axis=1)
out_data = data["DEATH_EVENT"]

scaler = StandardScaler()
scaler.fit(inp_data)
inp_data = scaler.transform(inp_data)

In [10]:
x_train, x_test, y_train, y_test = train_test_split(inp_data, out_data, test_size=0.2, stratify=out_data, random_state=2)

In [12]:
print("X_train: ", x_train.shape)
print("Y_train: ", y_train.shape)

print("X_test: ", x_test.shape)
print("Y_test: ", y_test.shape)

X_train:  (239, 12)
Y_train:  (239,)
X_test:  (60, 12)
Y_test:  (60,)


###Metodo Basico

In [13]:
model = svm.SVC()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score, roc_curve, classification_report

print("accuracy: ", accuracy_score(y_test, y_pred))
print("precision: ", precision_score(y_test, y_pred))
print("f1-score: ", f1_score(y_test, y_pred))
print("recall: ", recall_score(y_test, y_pred))
print("confusion matrix: \n", confusion_matrix(y_test, y_pred))
print("classification report: \n", classification_report(y_test, y_pred))

accuracy:  0.8166666666666667
precision:  0.7857142857142857
f1-score:  0.6666666666666666
recall:  0.5789473684210527
confusion matrix: 
 [[38  3]
 [ 8 11]]
classification report: 
               precision    recall  f1-score   support

           0       0.83      0.93      0.87        41
           1       0.79      0.58      0.67        19

    accuracy                           0.82        60
   macro avg       0.81      0.75      0.77        60
weighted avg       0.81      0.82      0.81        60



accuracy:  0.81, el modelo a predicho en el 81% de los casos de forma correcta

precision: 0.78, el modelo predice el 78% de los casos que una persona vive (1 es la variable objetivo). El modelo predice el 78% de los casos la variable con valor 1

recall: 0.57, de todas estimaciones de valor 1 (si muere) en el 0.57 son muertes verdaderas.

f1-scor: mide el balanc entre la presición y el recall. el valor debe estar cerca a 0.5


In [21]:
#encontrar la mejor combinación de hiperparametros
kernels = list(['poly', 'rbf', 'sigmoid'])
#kernels = list(['linear', 'poly', 'rbf', 'sigmoid'])
#linear: plano
#poly: curva
#rbf: funcion gaussiana
#sigmoid: hiperbolica

c = list([0.01, 0.1, 1, 10, 100])

#c = list([0.00001, 0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000])
#c: distancia con los vecotres de soporte

gammas = list([0.1, 1, 10, 100])
#gammas: distncia con las observaciones

In [22]:
from sklearn.model_selection import GridSearchCV

model = svm.SVC()
param_grid = {'kernel': kernels, 'C': c, 'gamma': gammas}

grid = GridSearchCV(model, param_grid, refit=True, verbose=3)
grid.fit(x_train, y_train)

grid.best_params_

Fitting 5 folds for each of 60 candidates, totalling 300 fits
[CV 1/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.688 total time=   0.0s
[CV 2/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.708 total time=   0.0s
[CV 3/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.667 total time=   0.0s
[CV 4/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.708 total time=   0.0s
[CV 5/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.681 total time=   0.0s
[CV 1/5] END .....C=0.01, gamma=0.1, kernel=rbf;, score=0.688 total time=   0.0s
[CV 2/5] END .....C=0.01, gamma=0.1, kernel=rbf;, score=0.688 total time=   0.0s
[CV 3/5] END .....C=0.01, gamma=0.1, kernel=rbf;, score=0.667 total time=   0.0s
[CV 4/5] END .....C=0.01, gamma=0.1, kernel=rbf;, score=0.667 total time=   0.0s
[CV 5/5] END .....C=0.01, gamma=0.1, kernel=rbf;, score=0.681 total time=   0.0s
[CV 1/5] END .C=0.01, gamma=0.1, kernel=sigmoid;, score=0.688 total time=   0.0s
[CV 2/5] END .C=0.01, gamma=0.1, kernel=sigmoid

{'C': 1, 'gamma': 0.1, 'kernel': 'sigmoid'}

In [23]:
grid.best_params_

{'C': 1, 'gamma': 0.1, 'kernel': 'sigmoid'}

In [24]:
model = svm.SVC(C=1, gamma=0.1, kernel='sigmoid')
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print("accuracy: ", accuracy_score(y_test, y_pred))
print("precision: ", precision_score(y_test, y_pred))
print("f1-score: ", f1_score(y_test, y_pred))
print("recall: ", recall_score(y_test, y_pred))
print("confusion matrix: \n", confusion_matrix(y_test, y_pred))
print("classification report: \n", classification_report(y_test, y_pred))

accuracy:  0.8166666666666667
precision:  0.8333333333333334
f1-score:  0.6451612903225806
recall:  0.5263157894736842
confusion matrix: 
 [[39  2]
 [ 9 10]]
classification report: 
               precision    recall  f1-score   support

           0       0.81      0.95      0.88        41
           1       0.83      0.53      0.65        19

    accuracy                           0.82        60
   macro avg       0.82      0.74      0.76        60
weighted avg       0.82      0.82      0.80        60



In [28]:
#encontrar la mejor combinación de hiperparametros
kernels = list(['linear'])

c = list([0.01, 0.1, 1, 5, 10, 20, 25, 30])
gammas = list([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])


In [29]:
model = svm.SVC()
param_grid = {'kernel': kernels, 'C': c, 'gamma': gammas}

grid = GridSearchCV(model, param_grid, refit=True, verbose=3)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits
[CV 1/5] END .C=0.01, gamma=0.01, kernel=linear;, score=0.771 total time=   0.0s
[CV 2/5] END .C=0.01, gamma=0.01, kernel=linear;, score=0.708 total time=   0.0s
[CV 3/5] END .C=0.01, gamma=0.01, kernel=linear;, score=0.729 total time=   0.0s
[CV 4/5] END .C=0.01, gamma=0.01, kernel=linear;, score=0.708 total time=   0.0s
[CV 5/5] END .C=0.01, gamma=0.01, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/5] END .C=0.01, gamma=0.02, kernel=linear;, score=0.771 total time=   0.0s
[CV 2/5] END .C=0.01, gamma=0.02, kernel=linear;, score=0.708 total time=   0.0s
[CV 3/5] END .C=0.01, gamma=0.02, kernel=linear;, score=0.729 total time=   0.0s
[CV 4/5] END .C=0.01, gamma=0.02, kernel=linear;, score=0.708 total time=   0.0s
[CV 5/5] END .C=0.01, gamma=0.02, kernel=linear;, score=0.766 total time=   0.0s
[CV 1/5] END .C=0.01, gamma=0.03, kernel=linear;, score=0.771 total time=   0.0s
[CV 2/5] END .C=0.01, gamma=0.03, kernel=linear

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1, 5, 10, 20, 25, 30],
                         'gamma': [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07,
                                   0.08, 0.09],
                         'kernel': ['linear']},
             verbose=3)

In [30]:
grid.best_params_

{'C': 1, 'gamma': 0.01, 'kernel': 'linear'}

In [31]:
model = svm.SVC(C=1, gamma=0.01, kernel='linear')
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print("accuracy: ", accuracy_score(y_test, y_pred))
print("precision: ", precision_score(y_test, y_pred))
print("f1-score: ", f1_score(y_test, y_pred))
print("recall: ", recall_score(y_test, y_pred))
print("confusion matrix: \n", confusion_matrix(y_test, y_pred))
print("classification report: \n", classification_report(y_test, y_pred))

accuracy:  0.8166666666666667
precision:  0.75
f1-score:  0.6857142857142857
recall:  0.631578947368421
confusion matrix: 
 [[37  4]
 [ 7 12]]
classification report: 
               precision    recall  f1-score   support

           0       0.84      0.90      0.87        41
           1       0.75      0.63      0.69        19

    accuracy                           0.82        60
   macro avg       0.80      0.77      0.78        60
weighted avg       0.81      0.82      0.81        60



###Smote: modelo para generar data sintetica en base a una data real

In [32]:
from imblearn.over_sampling import SMOTE

In [34]:
#luego de scalar
#X_train:  (239, 12)
#Y_train:  (239,)
#X_test:  (60, 12)
#Y_test:  (60,)

sms = SMOTE()
inp_data_smote, out_data_smote = sms.fit_resample(inp_data, out_data)
x_train_smote, x_test_smote, y_train_smote, y_test_smote = train_test_split(inp_data_smote, out_data_smote, test_size=0.2, stratify=out_data_smote, random_state=2)

In [35]:
print("x_train_smote: ", x_train_smote.shape)
print("y_train_smote: ", y_train_smote.shape)

print("x_test_smote: ", x_test_smote.shape)
print("y_test_smote: ", y_test_smote.shape)

x_train_smote:  (324, 12)
y_train_smote:  (324,)
x_test_smote:  (82, 12)
y_test_smote:  (82,)


In [36]:
#encontrar la mejor combinación de hiperparametros
kernels = list(['poly', 'rbf', 'sigmoid'])
c = list([0.01, 0.1, 1, 5, 10, 20, 25, 30])
gammas = list([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

model = svm.SVC()
param_grid = {'kernel': kernels, 'C': c, 'gamma': gammas}

grid = GridSearchCV(model, param_grid, refit=True, verbose=3)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits
[CV 1/5] END ...C=0.01, gamma=0.01, kernel=poly;, score=0.688 total time=   0.0s
[CV 2/5] END ...C=0.01, gamma=0.01, kernel=poly;, score=0.688 total time=   0.0s
[CV 3/5] END ...C=0.01, gamma=0.01, kernel=poly;, score=0.667 total time=   0.0s
[CV 4/5] END ...C=0.01, gamma=0.01, kernel=poly;, score=0.667 total time=   0.0s
[CV 5/5] END ...C=0.01, gamma=0.01, kernel=poly;, score=0.681 total time=   0.0s
[CV 1/5] END ....C=0.01, gamma=0.01, kernel=rbf;, score=0.688 total time=   0.0s
[CV 2/5] END ....C=0.01, gamma=0.01, kernel=rbf;, score=0.688 total time=   0.0s
[CV 3/5] END ....C=0.01, gamma=0.01, kernel=rbf;, score=0.667 total time=   0.0s
[CV 4/5] END ....C=0.01, gamma=0.01, kernel=rbf;, score=0.667 total time=   0.0s
[CV 5/5] END ....C=0.01, gamma=0.01, kernel=rbf;, score=0.681 total time=   0.0s
[CV 1/5] END C=0.01, gamma=0.01, kernel=sigmoid;, score=0.688 total time=   0.0s
[CV 2/5] END C=0.01, gamma=0.01, kernel=sigmo

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1, 5, 10, 20, 25, 30],
                         'gamma': [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07,
                                   0.08, 0.09],
                         'kernel': ['poly', 'rbf', 'sigmoid']},
             verbose=3)

In [37]:
grid.best_params_

{'C': 20, 'gamma': 0.01, 'kernel': 'sigmoid'}

In [38]:
model = svm.SVC(C=20, gamma=0.01, kernel='sigmoid')
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print("accuracy: ", accuracy_score(y_test, y_pred))
print("precision: ", precision_score(y_test, y_pred))
print("f1-score: ", f1_score(y_test, y_pred))
print("recall: ", recall_score(y_test, y_pred))
print("confusion matrix: \n", confusion_matrix(y_test, y_pred))
print("classification report: \n", classification_report(y_test, y_pred))

accuracy:  0.8166666666666667
precision:  0.75
f1-score:  0.6857142857142857
recall:  0.631578947368421
confusion matrix: 
 [[37  4]
 [ 7 12]]
classification report: 
               precision    recall  f1-score   support

           0       0.84      0.90      0.87        41
           1       0.75      0.63      0.69        19

    accuracy                           0.82        60
   macro avg       0.80      0.77      0.78        60
weighted avg       0.81      0.82      0.81        60

